# Generated by Django 4.2.7 on 2024-01-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_of_information',
            field=models.DateField(auto_now=True),
        ),
    ]
