# Generated by Django 4.2.7 on 2024-01-19 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.user_student')),
                ('number_of_bed_vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.vacancy')),
            ],
        ),
        migrations.DeleteModel(
            name='ViewRoom',
        ),
    ]
